// <auto-generated />
using System;
using System.Collections.Generic;
using Bara.API.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bara.API.DataContext.Migrations
{
    [DbContext(typeof(BaraContext))]
    [Migration("20251031084028_Reform")]
    partial class Reform
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bara.API.Scripts.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ScriptId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScriptId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1e0d885-ce96-47de-90c6-181a7b0510b4"),
                            Description = "Character-driven stories exploring emotion, conflict, and realism.",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("cdcba66a-ad75-4187-adaa-c19bf1359dc9"),
                            Description = "Light-hearted stories that aim to entertain and amuse audiences.",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("0d89a7ae-59a5-469e-b58c-e19f55176f81"),
                            Description = "High-paced stories with physical feats, chases, and intense conflict.",
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("eb7f1182-eb96-4ad4-b2d1-1c2dc0fdff79"),
                            Description = "Suspenseful stories that build tension and keep viewers on edge.",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("6d5ee5cb-b2eb-4ef5-b28f-b67655d07d57"),
                            Description = "Stories designed to scare, shock, or unsettle through fear or tension.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("ba04d138-837c-43ee-82ae-ad6811cc7b25"),
                            Description = "Stories focusing on love, relationships, and emotional intimacy.",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("365108ad-5700-4eac-922f-b4f8e0718f18"),
                            Description = "Stories exploring futuristic technology, space, and speculative ideas.",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("05ddf28e-27fe-4cdd-a455-04492f034cf1"),
                            Description = "Stories set in imaginary worlds with magic, myths, or supernatural elements.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("ee52f229-4646-4320-96d8-c18ab64efea7"),
                            Description = "Stories centered on solving puzzles, crimes, or hidden truths.",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("be73583d-c37a-49ca-837a-298ed3123e5a"),
                            Description = "Stories featuring journeys, exploration, and daring experiences.",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("7d2e8dd5-a9fa-4c2d-9e29-ceedc22dd292"),
                            Description = "Stories focused on criminal activity, law enforcement, and justice.",
                            Name = "Crime"
                        },
                        new
                        {
                            Id = new Guid("caae8c5a-c573-417f-9c11-ef4a3dba9cf5"),
                            Description = "Stories exploring the mind, identity, or emotional instability.",
                            Name = "Psychological"
                        },
                        new
                        {
                            Id = new Guid("eb925179-e538-47fa-92f9-d18e96c781e0"),
                            Description = "Stories set in or inspired by real historical periods and events.",
                            Name = "Historical"
                        },
                        new
                        {
                            Id = new Guid("7ef84244-b5b9-45df-abb3-a94ffe228032"),
                            Description = "Stories depicting conflict, survival, and humanity in wartime.",
                            Name = "War"
                        },
                        new
                        {
                            Id = new Guid("54cf7257-e6ac-4a3f-a12c-a84baf9ccadd"),
                            Description = "Dramatized portrayals of real-life people and their experiences.",
                            Name = "Biopic"
                        },
                        new
                        {
                            Id = new Guid("4b39daa3-0ce9-4ff6-8947-f9f5ebc155db"),
                            Description = "Stories about extraordinary individuals balancing power and morality.",
                            Name = "Superhero"
                        },
                        new
                        {
                            Id = new Guid("7eacd184-1c51-4c7a-8d23-ea9fd4055baf"),
                            Description = "Stories revolving around governance, ideology, and corruption.",
                            Name = "Political"
                        },
                        new
                        {
                            Id = new Guid("4bbe1b04-8b6a-4eb9-a973-c1f9e1b9766c"),
                            Description = "Humor that emerges from tragedy, irony, or moral ambiguity.",
                            Name = "Dark Comedy"
                        },
                        new
                        {
                            Id = new Guid("9bd42e1f-a91b-44e8-92e1-c4e74e9caf38"),
                            Description = "Love stories blended with humor and lighthearted tension.",
                            Name = "Romantic Comedy"
                        },
                        new
                        {
                            Id = new Guid("d9027750-a0ee-49aa-b98b-e2d079da6247"),
                            Description = "Stories set after civilization’s fall, exploring survival and renewal.",
                            Name = "Post-Apocalyptic"
                        },
                        new
                        {
                            Id = new Guid("ff8f9eea-69cc-41ed-a59f-604a716c68eb"),
                            Description = "Futuristic dystopias mixing tech, rebellion, and moral decay.",
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            Id = new Guid("499fd84c-21ac-47c1-a36e-dabd89095bd1"),
                            Description = "Epic tales combining magic, myth, and heroic journeys.",
                            Name = "Fantasy Adventure"
                        },
                        new
                        {
                            Id = new Guid("8914e52d-3fb2-45dd-9b83-6594642912de"),
                            Description = "Stories suitable for all ages, often with heartwarming or moral themes.",
                            Name = "Family"
                        },
                        new
                        {
                            Id = new Guid("e41616bf-18c9-42e6-9333-51ec92f6f313"),
                            Description = "Stories told through stylized or artistic animation.",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("acf19b34-b5e8-4b38-afa9-f2f7e3304345"),
                            Description = "Narratives where song and performance drive the story.",
                            Name = "Musical"
                        },
                        new
                        {
                            Id = new Guid("bd1e9340-d74a-44e5-ac46-fde205c21d96"),
                            Description = "Non-fictional storytelling capturing real-life events or people.",
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("9757f446-aecc-4c71-a108-a66461b8d3f3"),
                            Description = "Non-traditional or avant-garde narratives pushing boundaries.",
                            Name = "Experimental"
                        },
                        new
                        {
                            Id = new Guid("4d8e0058-c068-4082-afbe-5218e38818b3"),
                            Description = "Stylized stories featuring cynicism, fatalism, and moral ambiguity.",
                            Name = "Noir"
                        },
                        new
                        {
                            Id = new Guid("1f2f40a3-7650-4588-88c7-8dcbeac2e8c2"),
                            Description = "Stories inspired by spiritual, moral, or religious themes.",
                            Name = "Faith-Based"
                        },
                        new
                        {
                            Id = new Guid("c9293445-a881-4719-908a-3c396cfbcbe4"),
                            Description = "Stories addressing social issues, justice, and cultural reflection.",
                            Name = "Social Commentary"
                        },
                        new
                        {
                            Id = new Guid("9669cd2b-f528-4b44-a593-28a532d643e7"),
                            Description = "Stories centered on athletes, competition, and perseverance.",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("5307ea4f-4a38-4a8e-8dc2-4341333200cf"),
                            Description = "Stories about growth, identity, and the transition into adulthood.",
                            Name = "Coming-of-Age"
                        },
                        new
                        {
                            Id = new Guid("502c1f81-1409-4650-874f-82129b5c78fa"),
                            Description = "Real-world settings infused with subtle magical or surreal elements.",
                            Name = "Mystical Realism"
                        });
                });

            modelBuilder.Entity("Bara.API.Scripts.Models.Script", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CopyrightNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsScriptRegistered")
                        .HasColumnType("boolean");

                    b.Property<string>("Logline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnershipRights")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProducerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProofUrl")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationBody")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UploadedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WriterId")
                        .HasColumnType("uuid");

                    b.Property<string>("WriterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProducerId");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.HasIndex("WriterId");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("Bara.API.Scripts.Models.ScriptRelatedChats.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProducerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScriptId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScriptTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WriterId")
                        .HasColumnType("uuid");

                    b.Property<string>("WriterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Bara.API.Scripts.Models.ScriptRelatedChats.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Bara.API.Scripts.Models.ScriptTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProducerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ScriptCommentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScriptId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScriptTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("WriterAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WriterId")
                        .HasColumnType("uuid");

                    b.Property<string>("WriterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("WriterPaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WriterShare")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey");

                    b.HasIndex("ScriptCommentsId");

                    b.HasIndex("ProducerId", "ScriptId");

                    b.ToTable("ScriptTransactions");
                });

            modelBuilder.Entity("Bara.API.Transactions.Models.Escrow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("Escrow");
                });

            modelBuilder.Entity("Bara.API.Transactions.Models.PaymentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorizationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Reusable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentDetail");
                });

            modelBuilder.Entity("Bara.API.Transactions.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessCode")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransferCode")
                        .HasColumnType("text");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WalletID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionType");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Bara.API.Transactions.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LockedBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Bara.API.Users.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("ProofOfAddressDocument")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Bara.API.Users.Models.AuthProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfileSetupComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginDevice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastLoginIPAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLogoutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AuthProfiles");
                });

            modelBuilder.Entity("Bara.API.Users.Models.BankDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("BankType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("Bara.API.Users.Models.BioExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("WriterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WriterId");

                    b.ToTable("BioExperience");
                });

            modelBuilder.Entity("Bara.API.Users.Models.BlackListedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BlackListedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BlackListedUsers");
                });

            modelBuilder.Entity("Bara.API.Users.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text");

                    b.Property<string>("FileExtension")
                        .HasColumnType("text");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Bara.API.Users.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<List<string>>("Genre")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("IPDealType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SharePercentage")
                        .HasColumnType("integer");

                    b.Property<Guid>("WriterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WriterId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Bara.API.Users.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Gender");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IsBlacklisted");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Bara.API.Users.Models.Producer", b =>
                {
                    b.HasBaseType("Bara.API.Users.Models.User");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Producers", (string)null);
                });

            modelBuilder.Entity("Bara.API.Users.Models.Writer", b =>
                {
                    b.HasBaseType("Bara.API.Users.Models.User");

                    b.Property<bool>("IsPremiumMember")
                        .HasColumnType("boolean");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Writers", (string)null);
                });

            modelBuilder.Entity("Bara.API.Scripts.Models.Genre", b =>
                {
                    b.HasOne("Bara.API.Scripts.Models.Script", null)
                        .WithMany("Genres")
                        .HasForeignKey("ScriptId");
                });

            modelBuilder.Entity("Bara.API.Scripts.Models.Script", b =>
                {
                    b.HasOne("Bara.API.Users.Models.Producer", null)
                        .WithMany("PurchasedScripts")
                        .HasForeignKey("ProducerId");

                    b.HasOne("Bara.API.Users.Models.Writer", null)
                        .WithMany("Scripts")
                        .HasForeignKey("WriterId");
                });

            modelBuilder.Entity("Bara.API.Scripts.Models.ScriptRelatedChats.ChatMessage", b =>
                {
                    b.HasOne("Bara.API.Scripts.Models.ScriptRelatedChats.Chat", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bara.API.Scripts.Models.ScriptTransaction", b =>
                {
                    b.HasOne("Bara.API.Scripts.Models.ScriptRelatedChats.Chat", "ScriptComments")
                        .WithMany()
                        .HasForeignKey("ScriptCommentsId");

                    b.Navigation("ScriptComments");
                });

            modelBuilder.Entity("Bara.API.Transactions.Models.Escrow", b =>
                {
                    b.HasOne("Bara.API.Transactions.Models.PaymentTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId");

                    b.HasOne("Bara.API.Transactions.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId");

                    b.Navigation("Transaction");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Bara.API.Transactions.Models.PaymentDetail", b =>
                {
                    b.HasOne("Bara.API.Users.Models.User", null)
                        .WithMany("PaymentDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bara.API.Transactions.Models.PaymentTransaction", b =>
                {
                    b.HasOne("Bara.API.Users.Models.User", null)
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bara.API.Transactions.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletID");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Bara.API.Transactions.Models.Wallet", b =>
                {
                    b.HasOne("Bara.API.Users.Models.User", null)
                        .WithOne("Wallet")
                        .HasForeignKey("Bara.API.Transactions.Models.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bara.API.Users.Models.Address", b =>
                {
                    b.HasOne("Bara.API.Users.Models.User", null)
                        .WithOne("Address")
                        .HasForeignKey("Bara.API.Users.Models.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bara.API.Users.Models.AuthProfile", b =>
                {
                    b.HasOne("Bara.API.Users.Models.User", null)
                        .WithOne("AuthProfile")
                        .HasForeignKey("Bara.API.Users.Models.AuthProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bara.API.Users.Models.BankDetail", b =>
                {
                    b.HasOne("Bara.API.Users.Models.User", "User")
                        .WithMany("BankDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bara.API.Users.Models.BioExperience", b =>
                {
                    b.HasOne("Bara.API.Users.Models.Writer", "Writer")
                        .WithMany("Experiences")
                        .HasForeignKey("WriterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("Bara.API.Users.Models.BlackListedUser", b =>
                {
                    b.HasOne("Bara.API.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bara.API.Users.Models.Document", b =>
                {
                    b.HasOne("Bara.API.Users.Models.User", null)
                        .WithOne("Document")
                        .HasForeignKey("Bara.API.Users.Models.Document", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bara.API.Users.Models.Service", b =>
                {
                    b.HasOne("Bara.API.Users.Models.Writer", "Writer")
                        .WithMany("Services")
                        .HasForeignKey("WriterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("Bara.API.Users.Models.Producer", b =>
                {
                    b.HasOne("Bara.API.Users.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Bara.API.Users.Models.Producer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bara.API.Users.Models.Writer", b =>
                {
                    b.HasOne("Bara.API.Users.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Bara.API.Users.Models.Writer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bara.API.Scripts.Models.Script", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Bara.API.Scripts.Models.ScriptRelatedChats.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Bara.API.Transactions.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Bara.API.Users.Models.User", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("AuthProfile")
                        .IsRequired();

                    b.Navigation("BankDetails");

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("PaymentDetails");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("Bara.API.Users.Models.Producer", b =>
                {
                    b.Navigation("PurchasedScripts");
                });

            modelBuilder.Entity("Bara.API.Users.Models.Writer", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Scripts");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
